name: Github Pages Deploy

on:
  push:
    branches:
      - "devel"

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.22.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'

      - name: Setup G++
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install
        run: npm install --force

      - name: Build
        run: npm run build  
  
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build   